export const PROTOCOL = {
  player: "player",
  protocol: "protocol",
  init: "init",
  pluginVersion: "pluginversion",
  clientNotAllowed: "notallowed",
  playerStatus: "playerstatus",
  playerRepeat: "playerrepeat",
  playerScrobble: "scrobbler",
  playerShuffle: "playershuffle",
  playerMute: "playermute",
  playerPlayPause: "playerplaypause",
  playerPrevious: "playerprevious",
  playerNext: "playernext",
  playerStop: "playerstop",
  playerState: "playerstate",
  playerVolume: "playervolume",
  nowPlayingTrack: "nowplayingtrack",
  nowPlayingCover: "nowplayingcover",
  nowPlayingPosition: "nowplayingposition",
  nowPlayingLyrics: "nowplayinglyrics",
  nowPlayingRating: "nowplayingrating",
  nowPlayingLfmRating: "nowplayinglfmrating",
  nowPlayingDetails: "nowplayingdetails",
  nowPlayingList: "nowplayinglist",
  nowPlayingListPlay: "nowplayinglistplay",
  nowPlayingListRemove: "nowplayinglistremove",
  nowPlayingListMove: "nowplayinglistmove",
  nowPlayingQueue: "nowplayingqueue",
  nowPlayingListChanged: "nowplayinglistchanged",
  ping: "ping",
  pong: "pong",
  playerPlay: "playerplay",
  playerPause: "playerpause",
  playlistList: "playlistlist",
  playlistPlay: "playlistplay",
  libraryBrowseGenres: "browsegenres",
  libraryBrowseArtists: "browseartists",
  libraryBrowseAlbums: "browsealbums",
  libraryBrowseTracks: "browsetracks",
  verifyConnection: "verifyconnection",
  radioStations: "radiostations",
  commandUnavailable: "commandunavailable",
  playerOutput: "playeroutput",
  playerOutputSwitch: "playeroutputswitch",
  libraryCover: "libraryalbumcover",
  libraryPlayAll: "libraryplayall",
  discovery: "discovery",
  toggle: "toggle",
  unknownCommand: "unknowncommand"
} as const;

export type ProtocolContext = (typeof PROTOCOL)[keyof typeof PROTOCOL];

export const CURRENT_PROTOCOL_VERSION = 4;
export const MIN_SUPPORTED_PROTOCOL_VERSION = 2;
export const PAGE_LIMIT = 800;
